spring.application.name=quackstars
server.port=${SERVER_PORT:8081}
spring.profiles.default=db
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
server.compression.enabled=true
server.compression.mime-types=application/json,application/problem+json,text/plain
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}
logging.level.it.tdlight=WARN
